name: Docker Multi-platform CI

on:
  push:
    branches: master

env:
  V2RAY_VERSION: 4.33.0

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            kotaimen/v2fly:latest
            kotaimen/v2fly:${{ env.V2RAY_VERSION }}
          build-args: |
            V2RAY_VERSION=${{ env.V2RAY_VERSION }}
