name: Build and Push

on:
  push:
    branches:
      - main

env:
  V2FLY_VERSION: ${{ vars.V2FLY_VERSION }}
permissions:
  contents: read
  packages: write

jobs:

  Release:
    name: Release
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
          set: |
            v5.args.V2FLY_VERSION=${{ env.V2FLY_VERSION }}
