name: ci

on:
  push:
    branches:
      - main

jobs:

  Release:
    name: Release
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}     
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          set: |
            v2fly.args.V2RAY_VERSION=${{ secrets.V2RAY_VERSION }}
