name: Build and Push

on:
  push:
    branches:
      - main

env:
  V2RAY_VERSION: 5.16.1

jobs:

  Release:
    name: Release
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v5
        with:
          push: true
          set: |
            v5.args.V2RAY_VERSION=${{ env.V2RAY_VERSION }}
